Text input 공통 컴포넌트 개발
SystemConsultantGroup/foodhub-frontend pull request #11
Opened 2023-08-08 07:56 UTC by sera2002

작성자: @sera2002 

Related to #{이슈 번호 기입}

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- Props
  - label (선택)
  - placeholder (선택)
  - condtionList (선택) : 입력 조건 리스트 (사용자에게 단순히 보여주는 용도)
  - conditionChecks (선택) : 입력 조건을 체크할 함수 리스트
  - multiline (선택, default는 false) : true이면 textarea로 설정
  - errorMessage (선택, default는 "잘못된 입력입니다.") : 조건에 부합하지 않는 경우 표시할 error 메세지

## 비고

2023-08-08 12:24 UTC, jaychang99 requested changes
수고하셨습니다! 질문과 몇 가지 코멘트를 달았습니다!

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/CheckIcon.tsx
> +      alt="입력 완료 체크 아이콘"
오 alt Text 좋습니다. 👍

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/CheckIcon.tsx
> +const CheckIcon: FC<Props> = ({ size }) => {
혹시 이 아이콘이 가장 많이 쓰일 법한 사이즈가 따로 있을까요~?
있다면 `size` 를 optional 로 정의하고 기본 사이즈를 잡아놓는 것도 매번 쓰는 데에 편리할 수 있을 것 같습니다!

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +
@hoon5083 @sera2002  오.. 이건 컨벤션의 영역일 것 같기는 한데, 처음에 제가 styles.tsx 파일을 따로 만들지 않은 것으로 계획한 것 (어울림, scg 홈페이지 프로젝트와 달리) 은 하나의 `<EmotionWrapper />` 안에 className 또는 sass 형식으로 그 래퍼 안의 모든 마크업에 대한 스타일을 제공하기 위한 것이긴 했습니다. 

이거를 통일하는 것이 좋을까요? (진짜 질문)

(참고: 약간 이런 식의 활용입니다: [PageMarker.tsx](https://github.com/SystemConsultantGroup/foodhub-frontend/blob/feature/page-structure-setup/src/components/pageMarker/PageMarker.tsx))

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +        ></InputComponent>
self-closing tag 로 처리하면 가독성이 좋아질 것 같아요..!

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +        {value && isValid && !isFocused && <CheckIcon size={20} />}
혹시 체크 아이콘을 디자인 안 처럼 input 안에 띄우는 것이 가능할까요..~?

* As-is

| focused | not focused |
| --- | --- |
| <img width="375" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/89bb6986-9752-4559-a383-5f4a73f144f8"> |<img width="372" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/ec16c8e9-2ce8-49d8-92af-3dc5e832bd02"> |

---

디자인 안

<img width="325" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/59fbc0d3-8282-4f5c-97a1-13f78c8ea067">

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +  errorMessage = "잘못된 입력입니다.",
오 errorMessage 를 받아오는 것은 좋습니다. 그런데 errorMessage 가  conditionChecks 에 의존적일 수 있을 것 같아 conditionChecks 에서 condition 들을

```tsx 
{
  condition: (text: string) => boolean;
  messageOnError: string
}
```

예시

```tsx
const conditionCheckList = [
  {
    condition: (value) => value.includes("@"),
    messageOnError: "이메일 형식으로 입력해주세요"
  }, 
  {
    condition: (value) => value.length >= 20,
    messageOnError: "이메일은 최소 20자 이상이어야 합니다. "
  }, 
]
```

처럼 받아와 여러 개의 validation 조건이 있을 경우 validation 상황에 따라 특정 에러 메시지를 출력해볼 수도 있을 것 같습니다!

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +  conditionChecks?: ((text: string) => boolean)[];
오 정말 사소한건데 위에도 배열을 `*List` 로 해주셔서 밑에도 `conditionCheckList` 로 가면 어떨까 싶습니다!

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +  };
포커싱이 되면 특정 로직이 실행되는 것은 좋은 것 같습니다. 그러나, 이렇게 처리할 경우 처음부터 무조건 빨간 박스가 뜰 것 같습니다. (물론 비밀번호 등의 경우 이렇게 처음부터 보안강도 validation 을 하는 곳도 있으나, ) 모든 input 에 대해 클릭하자마자 빨간색으로 표시되는 것은 UX 에 조금 좋지 않을 것 같습니다 🙂 

최초로 focus 했을 때는 validate 하지 않고, 최초 focus 후 blur 이벤트가 1회라고 발생했다면 validate 하는 로직은 어떨까요~?

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +
오 이렇게 될 경우 이 컴포넌트를 사용하는 곳에서는 어떤 식으로 이 input 의 값을 받아갈 수 있을까요~?

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +        : setBorderStyle("default");
오... 3항 연산자가 중첩되어 가독성이 조금 저하되는 것 같습니다. 

그리고 focus 의 경우 특별한 경우가 아니라면 css 의 네이티브 `:&focus` 를 이용하는 것은 어떨까요? `blur` 상태도 결국 클릭하지 않은 기본 상태일 것 같은데 JS 에 따라 validate 성공/실패 여부만 바꾸어줘도 괜찮지 않을까요~?

그리고 성공 실패 여부도 css 의 focus, active 와 같은 pseudo class 처럼 다룰 수 있긴 합니다. 아래와 같은 방식으로요~

```tsx
import styled from "@emotion/styled";
import { useState } from "react";

interface Props {}

const PageDemo = ({}: Props) => {
  const [status, setStatus] = useState("success");

  return (
    <EmotionWrapper>
      <input data-status={status} />
    </EmotionWrapper>
  );
};

export default PageDemo;

const EmotionWrapper = styled.div`
  input {
    width: 100px;
    height: 100px;
    border: 1px solid black;

    &[data-status="success"] {
      background-color: green;
    }
  }
`;
```

`data-` 속성은 html  네이티브 속성이며, 화면에 보이지 않는 특정 데이터를 HTML  상에 넣어두고 싶을 때 사용할 수 있습니다! 

참고 문서: https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

2023-08-08 12:24 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +};
조금더 CSS 스럽게 쓸 수 있을 것 같습니다!

(invalid, success 상태 제외)

2023-08-08 12:30 UTC, hoon5083 commented on src/components/inputs/TextInput/TextInput.tsx
> +
아 네네 저도 Wrapper는 단 하나의 EmotionWrapper를 마치 styles 파일처럼 활용하는게 괜찮아 보였습니다 :)

2023-08-08 12:31 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +`;
아래에 focus 시 발생하는 기본 `outline` 속성 제거해주시면 더욱 저희 디자인 시스템과도 더 잘 부합할 것 같습니다~ 🙂 

![image](https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/aad58a69-bf80-4786-b1c6-89973dce7424)

2023-08-08 12:31 UTC, kanghoon-dev commented on src/components/inputs/TextInput/TextInput.tsx
> +  conditionChecks?: ((text: string) => boolean)[];
이게 복수형을 사용할때 애매한 경우가 *List로 하면 그나마 통일성이 나오는거 같더라구요....ㅎㅎ

2023-08-08 12:32 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +  conditionChecks?: ((text: string) => boolean)[];
오 넵 동의합니다. ㅋㅋㅋㅋ 이러다가 영어 불규칙 복수형까지 알아내야 할수도...

2023-08-08 15:24 UTC, sera2002 commented on src/components/inputs/TextInput/CheckIcon.tsx
> +const CheckIcon: FC<Props> = ({ size }) => {
피그마 상에서 보면 크기가 제각각이긴 한데, 일단 제일 많은 16px로 설정해놓겠습니다!

2023-08-08 15:29 UTC, sera2222 commented on src/components/inputs/TextInput/TextInput.tsx
> +        {value && isValid && !isFocused && <CheckIcon size={20} />}
음.. 사실 그걸 어떻게 하는지 모르겠어서 일단 밖에다가 두었는데, 한 번 해보겠습니다..!

2023-08-08 15:40 UTC, sera2222 commented on src/components/inputs/TextInput/TextInput.tsx
> +  };
```suggestion
   // 입력된 텍스트의 조건 확인을 수행하여 isValid 상태 업데이트
    if (isFocused && isBlurred && value != "") {
      setIsValid(conditionCheckList ? conditionCheckList.every((check) => check(newValue)) : true);
    }
  };
```
Blur 이벤트 최초 발생 후에 validate 하도록 수정했습니다!

2023-08-08 15:45 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +
오 그러네요.. onChange로 콜백 함수 받아오도록 수정하겠습니다.

2023-08-08 23:17 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +        {value && isValid && !isFocused && <CheckIcon size={20} />}
@sera2002  오 넵 조금 까다로운 작업이긴하죠 ㅋㅋㅋ

보통 상위 element 에 position: relative 를 걸고, 직속 하위 element 에 position:absolute 를 건 다음 하위 element 에 top, bottom, right, left 속성으로 조절을 할 수도 있습니다.

2023-08-08 23:18 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +  };
넵 수정 감사합니다~~

2023-08-08 23:21 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +
오호 넵넵 위와 같은 방법도 좋고 input 태그에 name 값을 설정하여 상위 어디에서라도 form 태그에만 감싸져있다면 불러올 수 있도록 하는 것도 괜찮을 것 같아요! 

그리고 어느 방법을 쓰더라도 외부에서 '제출' 을 눌렀을 때 validate 되지 않은 데이터가 있을 경우 제출되지 않게 하는 로직도 필요하지 않을까 싶습니다....!

2023-08-13 12:00 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +
해당 내용 반영하여 수정하였습니다!

2023-08-13 14:51 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +        : setBorderStyle("default");
해당 부분 [이 커밋](https://github.com/SystemConsultantGroup/foodhub-frontend/pull/11/commits/ad7cd519849ed2faea1340d7dd04cb3aacd61161)에서 수정했습니다!

2023-08-13 14:52 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +};
css스럽다는게 어떤 건지 잘 모르겠는데, 혹시 좀 더 자세히 말씀해 주실 수 있을까요? @jaychang99

2023-08-13 15:01 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +
validate 되지 않은 데이터 여부만 상위 컴포넌트에 전달해서, 제출되지 않게 하는건 상위 컴포넌트에서 컨트롤하게 해도 될까요? @jaychang99

2023-08-13 15:04 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +
name 설정하는 것도 좋을 것 같긴 하네요.. name에 들어갈 값도 props로 받아오도록 수정하겠습니다!

2023-08-15 00:56 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +
@sera2002  오 커밋 링크 바로 달아주시니 확인하기 아주 편하네요! 감사합니다! resolve 시키겠습니다!

2023-08-15 01:08 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +};
@sera2002 
앗 넵넵 그것을 생각하였습니다. 
아래와 같이 생각하였었는데

* 기존의 `focused` 케이스: `&:focus` 로 대체 가능
* 기존의 `blur` 케이스는 ..(?)
* 기존의 `lnvalid` 케이스는  (?)
* 기존의 default 케이스는 기본 css 스타일로 대체 가능

다시 생각해보니 케이스가 조금 있네요... 그대로 가는 것도 좋을 것 같습니다... 죄송합니다 😓

2023-08-16 09:15 UTC, sera2002 commented
음 근데 현재 서버에 이미 있는 값 넣어주는 부분이 없는 것 같아서 빠르게 추가하겠습니다..!

2023-08-16 09:21 UTC, sera2002 commented
그리고 multiline이 true일 때 label이 안보이네요,, 이 부분도 수정하겠습니다.

2023-08-16 09:37 UTC, jaychang99 reviewed
커멘트를 하나 남겼습니다!

2023-08-16 09:37 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +            name={name ? name : label}
오 name prop 추가해주신 점 확인하였습니다. 그런데 `label` 값으로 fallback 할 필요 없이 그냥 `name` 만 써도 될 것 같습니다..!  (name prop 주어지지 않은 경우 그냥 undefined 로 처리) name prop 을 넣지 않았는데 label 키값으로 name 이 생기면 사용하는 쪽에서 헷갈릴 수 있을 것 같습니다. 

```suggestion
            name={name}
```

2023-08-16 09:51 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +            name={name ? name : label}
넵 반영하였습니다!

2023-08-16 09:52 UTC, jaychang99 approved these changes
LGTM 입니다. 수고하셨습니다!

2023-08-17 08:23 UTC, hoon5083 commented on src/components/inputs/TextInput/TextInput.tsx
> +
이거 반영 상황 어떻게 됐을까요? 확인하시고 스레드 처리 부탁드립니다 :) @jaychang99 @sera2002

2023-08-17 08:23 UTC, hoon5083 approved these changes
수고하셨습니다!

2023-08-17 09:28 UTC, sera2002 commented on src/components/inputs/TextInput/TextInput.tsx
> +
반영된 상태입니다! @jaychang99

2023-08-17 12:23 UTC, jaychang99 commented on src/components/inputs/TextInput/TextInput.tsx
> +
@sera2002 @hoon5083 넵 확인하였습니다! 늦은 확인 죄송합닌다. 🙇

2023-08-17 12:51 UTC, merged