Drop Down 컴포넌트 개발
SystemConsultantGroup/foodhub-frontend pull request #12
Opened 2023-08-14 17:50 UTC by sera2002

작성자: @sera2002 

Related to #{이슈 번호 기입}

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- DropDown 컴포넌트 개발
  - Props
    - name (선택) : 사용자가 보기에 식별하기 편하게 일단 뚫어놓긴 했는데, 컴포넌트 자체에서 어떻게 쓰일 수 있을지는 잘 모르겠습니다..
    - label (선택)
    - onSelectValueChange (선택) : 선택된 option의 value 전달하는 콜백 함수

- DropDownOption 컴포넌트 개발
  - Props
    - value (필수)
    - isSelected (선택, default는 false) : 해당 옵션을 default로 선택하도록 할 지 결정
    - disabled (선택, default는 false)
  

## 비고

- DropDown 컴포넌트 사용 예시
```
<DropDown name="dropdown" onSelectValueChange={handleSelectValueChange}>
            <DropDown.Option value="option1">Option1</DropDown.Option>
            <DropDown.Option value="option2" isSelected={true}>
              Option2
            </DropDown.Option>
            <DropDown.Option value="option3">Option3</DropDown.Option>
</DropDown>
```

2023-08-14 18:19 UTC, hoon5083 requested changes
수고하셨습니다! 몇가지 제안사항입니다 :)

2023-08-14 18:19 UTC, hoon5083 commented on src/components/dropdown/items/DropDownOption.tsx
> +  }
color 속성은 line 40에서 정의한게 중복해서 들어가고 있는 것 같습니다 :)

2023-08-14 18:19 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +        )}
오 매번 그냥 Array.map 만 사용했는데 이렇게 할 수도 있나요? @jaychang99

2023-08-14 18:19 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +              onClick: () => handleOptionClick(child.props.value, child.props.children, index),
음 혹시 인덱스를 아예 사용하지 않고 고유한 children 쪽 데이터의 고유값만 사용해서 할 수가 있을까요?
@jaychang99 컴포넌트 쪽 map 에서 index 쓰면 괜히 찜찜해서요 하핳....

2023-08-14 18:19 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +    });
음 이걸 그냥 onClick 콜백함수에서 관리해도 되지 않을까요? 
selectedOption state에 모든 값을 다 담을 필요는 없을거 같습니다. 어떤 것이 선택됐는지만 나타낼 수 있으면 충분하지 않을까 싶어서요 :)

2023-08-15 00:40 UTC, jaychang99 requested changes
수고하셨습니다!
몇 가지 커멘트와 질문을 남겨두었습니다! 🙂

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/items/DropDownOption.tsx
> +    cursor: not-allowed;
오 꼼곰한 커서처리 좋습니다!

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/items/DropUpIcon.tsx
> +const DropUpIcon: FC<Props> = ({ size = 16, style }) => {
정말 사소한 이름관련이지만, Dropup 이라는 UI 요소가 다른 의미로도 쓰이기도 합니다. (눌렀을 때 옵션들이 아래로 떨어져서 보이는 것이 아니라 위로 떨어지는 경우...) 그래서 올라가는 / 내려가는 화살표 아이콘 이름을 `dropdownUpIcon` `dropdownDownIcon` 등으로 dropdown 이라는 풀 이름을 포함하는 것이 어떨까요~?

또한 이와 관련해서 dropdown 의 경우 화면 리소스가 부족할 경우 (화면 맨 아래에 배치된 경우 등) 위로 옵션들이 표시되게도 옵션을 주면 (dropup) 좋을 것 같습니다만, 저희 프로젝트에서 그렇게 자주 발생할 것 같지는 않습니다! 지금 당장에는 고려하지 않아도 될 것 같습니다. 

약간 아래와 같은 것이 DropUp 이라고 할 수 있을 거 같네요! 🙂 

<img width="391" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/63b60ef5-2123-4a2a-aa04-f406b788227f">

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +const DropDown = ({ children, label, onSelectValueChange }: Props) => {
컴포넌트 이름은 `DropDown` 인 데 반해, 폴더와 파일 이름 등은 `Dropdown.tsx` 인 것 같습니다. 

이 부분도 통일하면 좋을 것 같습니다...!

드롭다운이 단어는 두 개 이지만 하나의 UI 컴포넌트를 가리키니 파일명에 적어주신 것 처럼 `Dropdown` 으로 가는 것도 좋을 것 같습니다! 🍀 

(참고: 파일의 대소문자를 변경할 시 `already included file name` 이라는 에러가 뜰 수 있습니다! 그런 경우 모든 파일에서 변경된 대소문자 파일 및 폴더명들이 제대로 변경되었는지 확인부탁드립니다!)

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/items/DropDownOption.tsx
> +      className={isSelected ? "selected" : ""}
오 조건부 className 부여 좋네요 👍

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  const handleOptionClick = (value: string, text: React.ReactNode, index: number) => {
여기 및 `TSelectedOption` 에서 `text` 의 타입이 `string` 이 아닌 `ReactNode` 로 되어 있는 것 같습니다. `text` 를 유지하려면 타입을 `string`으로, `ReactNode` 를 유지하려면 `children`, 또는 `element` (?) 와 같은 node 이다 라는 것을 나타낼 수 있는 키값 (인자명) 이 어떨까요~?

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +const DropDown = ({ children, label, onSelectValueChange }: Props) => {
저는 로컬에서 이 브랜치 아래와 같은 에러가 뜨고 있습니다!
dropdown  과 dropDown 폴더명이 일부 달라서 발생하는 문제 같습니다...

<img width="1075" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/3bbb0064-63ff-4a75-9ea5-acf999619c79">

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +const DropDown = ({ children, label, onSelectValueChange }: Props) => {
음.. 이 에러가 있는 상태로 저는 푸시 및 커밋이 되지 않긴 한데 이상하네용...

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +      {label && <span className="label">{label}</span>}
라벨과 드롭다운 사이 간격이 추가되어야 할 것 같아요!

<img width="201" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/b144ef47-6b42-4363-95a4-5d092562b464">

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    };
사소한 것이지만, 객체에서 키값 이름과 키값의 값 (변수) 가 동일하면 한번만 써주어도 됩니다..!

```suggestion
    const newSelectedOption: TSelectedOption = { index, text, value };
```

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
이 prop 의 목적은 내부적으로선택된 값이 바뀔 때 외부에서 넣어준 callback 함수를 실행하여 주는 것 같은데 맞나용~?

그렇다면 이 dropdown 의 초기값을 넣어줄 수 도 있어야 할 것 같습니다!

이를테면 form 을 수정한다든가 할 때 기존에 select 된 값을 채워넣어주는 기능이요!

<img width="347" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/9b71e729-8ea7-4867-80eb-3e7538bc058a">

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    };
혹시 이 함수를 `useEffect()` 안에다가 정의하신 특별한 이유가 있나용~? (단순 궁금증 입니다)

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +              onClick: () => handleOptionClick(child.props.value, child.props.children, index),
@hoon5083 @sera2002  음... `value` 값으로 비교하는 것은 어떨까요 그러면?

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +        )}
@hoon5083 오 지금은 오히려 자식 node 들 (children) 그 자체로는 배열이 아니기 때문에 `Array.map` 사용은 어려울 것 같습니다. 

[React Children API](https://react.dev/reference/react/Children) 를 사용하여 1계층 자식node 들을 내부적으로 배열로 변환한다음 매핑시겨주는 방식을 쓰신 것 같네요!

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  }, []);
여기 의존성 배열에 `children` 이 있어야 할 것 같습니다!

children 이 없으면

```
<DropDown label="드롭다운">
        <DropDown.Option value="1" isSelected={selectedIndex === 1}>
          1
        </DropDown.Option>
        <DropDown.Option value="2" isSelected={selectedIndex === 2}>
          2
        </DropDown.Option>
        <DropDown.Option value="3" isSelected={selectedIndex === 3}>
          3
        </DropDown.Option>
        <DropDown.Option value="4" isSelected={selectedIndex === 4}>
          4
        </DropDown.Option>
      </DropDown>
```

위와 같은 상황에 `selectedIndex` 가 state 라고 가정했을 때에, `selectedIndex` 의 변화에 따라 이 값이 변하지가 않을 것 같습니다.

2023-08-15 00:40 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    });
@hoon5083 혹시 정확히 어떤 부분까지를 콜백함수로 관리하는 지 조금 더 구체적으로 설명해주실 수 있으실까요~?

2023-08-15 05:19 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +    });
아 각각의 선택항목에 onClick을 줘도 되지 않을...까 했는데 이건 좀 생각해 봐야할 것 같네요 한번 써보고 공유하겠습니다!

2023-08-15 05:30 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +              onClick: () => handleOptionClick(child.props.value, child.props.children, index),
value 값으로 비교하는 것 좋은 것 같습니다!

2023-08-15 05:36 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +const DropDown = ({ children, label, onSelectValueChange }: Props) => {
원격 저장소에서 폴더명 변경한게 적용이 안되어서 제 로컬에서는 에러가 잡히지 않은 거였습니다..
폴더명, 파일명 모두 Dropdown으로 통일하도록 하겠습니다!

2023-08-15 06:00 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +    };
음.. 별 의미는 없는데 지금 보니까 그냥 밖으로 빼줘도 되겠네요

2023-08-15 06:42 UTC, sera2002 commented on src/components/dropdown/items/DropUpIcon.tsx
> +const DropUpIcon: FC<Props> = ({ size = 16, style }) => {
DrondownUpIcon으로 네이밍 수정했습니다.

2023-08-15 06:43 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +  const handleOptionClick = (value: string, text: React.ReactNode, index: number) => {
children으로 키값 변경하였습니다.

2023-08-15 06:43 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +  }, []);
넵 의존성 배열에 children 추가하였습니다.

2023-08-15 06:50 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
@sera2002 아 근데 각 select option 의 isSelected props 로 넘겨줄 수는 있낀 하네용... 그래도 value 그 자체로 넘겨줄 수도 있으면 매번 반복문 돌려 어떤 항목이 선택되었는지 확인하지 않아도 되어 좋을 것 같습니다!

2023-08-15 06:51 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    });
@hoon5083 아.. 각각의 항목이요.. 그렇네요 그렇게 할 수도 있을 것 같긴하네요 넵넵

2023-08-15 06:53 UTC, jaychang99 commented on src/components/dropdown/items/DropUpIcon.tsx
> +const DropUpIcon: FC<Props> = ({ size = 16, style }) => {
@sera2002 오 넵 감사합니다. 앗 세라님 `drop-down-line.svg` 와 `drop-up-line.svg` 도 수정 가능하실까요~?

2023-08-15 06:54 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +const DropDown = ({ children, label, onSelectValueChange }: Props) => {
오 넵넵 에러 해결 확인했습니다~

2023-08-15 06:57 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +              onClick: () => handleOptionClick(child.props.value, child.props.children, index),
@sera2002 앗 혹시 removeEventListener 이 없어진 것 같은데 확인 가능하실까요~?

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/Dropdown.tsx
> +      {label && <span className="label">{label}</span>}
넵 의견 감사합니다. 간격 추가하였습니다!

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/items/DropDownOption.tsx
> +  }
넵 수정하였습니다!

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/Dropdown.tsx
> +    };
오.. 넵 반영하였습니다!

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/items/DropUpIcon.tsx
> +const DropUpIcon: FC<Props> = ({ size = 16, style }) => {
앗 넵넵 `dropdown-down-line.svg`와 `dropdown-up-line.svg`로 변경하였습니다!

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/Dropdown.tsx
> +              onClick: () => handleOptionClick(child.props.value, child.props.children, index),
@jaychang99 엇 그러네요..! 다시 추가했습니다.

2023-08-15 13:18 UTC, sera2222 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
외부에서 isSelected Props로 설정한 초기값은 콜백 함수 실행 시 넘어가도록 수정하긴 했는데, 
value 그 자체로 넘겨준다는게 defaultValue Props를 새로 생성해서 value만 따로 넘겨주도록 한다는 말씀이신가요? @jaychang99

2023-08-15 13:26 UTC, jaychang99 commented on src/components/dropdown/items/DropUpIcon.tsx
> +const DropUpIcon: FC<Props> = ({ size = 16, style }) => {
오 넵 감사합니다!

2023-08-15 13:32 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
@sera2002 음 넵넵 defaultValue 같은 느낌이긴해요!
API 통신을 할 때에는 주소 값이 value? 로 내려올 것 같은데 이를 프론트에서 한번 더 어떤 dropdown.option 에 isSelected 가 true 로 들어가야할 지 고민해야 할 것 같아서요!

2023-08-15 13:36 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +    });
저 부분이, 처음에 default로 선택된 항목을 처리하려고 했던 부분이었는데, 저 코드에서는 그게 제대로 동작하지 않던 상태여서 아래와 같이 수정했습니다.
```
// 자식 옵션 중에서 isSelected 값이 true인 옵션을 찾아서 selectedOption 초기화
    if (selectedOption === null) {
      React.Children.forEach(children, (child) => {
        if (React.isValidElement<OptionProps>(child) && child.props.isSelected) {
          const newSelectedOption: TSelectedOption = {
            children: child.props.children,
            value: child.props.value,
          };
          if (onSelectValueChange) {
            onSelectValueChange(child.props.value);
          }
          setSelectedOption(newSelectedOption);
          return;
        }
      });
    }
```
각각의 선택항목에다가 아래와 같은 onClick 함수는 주고 있는 상태이긴 합니다
```
const handleOptionClick = (value: string, children: React.ReactNode) => {
    const newSelectedOption: TSelectedOption = {
      children,
      value,
    };
    setSelectedOption(newSelectedOption);
    setIsOpen(false);

    if (onSelectValueChange) {
      onSelectValueChange(value);
    }
  };
```
음.. selectedOption state에 모든 값을 넣지 않고 최소한의 값만 담도록 하는 것은 조금 고민해보겠습니다..!

2023-08-15 13:55 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    });
@sera2002 오 넵 설명 감사드립니다. 
@hoon5083 음 .. 혹시 [최소한의 값만 담도록 하는 것] 이 어떤 것을 의미하신 것일까요~?
index, value 등을 담지 않고, 현재 선택된 값만 담도록 하는 것인가요?

2023-08-15 14:21 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
@jaychang99 오 그러네요! Dropdown 컴포넌트에 value props 추가하였고, 해당 value에 해당하는 option이 default로 나타나도록 수정하였습니다.

2023-08-15 15:45 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +    });
네넵 현재 선택된 값의 index 정도만...? 생각했습니다

2023-08-16 01:24 UTC, jaychang99 commented
@sera2002 

음.. 아래와 같이 세팅하였을 때 처음에는 드롭다운이 아래로 펼쳐졌는데 이제는 아예 드롭다운이 나오지 않고 있습니다.
혹시 이 부분 재현되실까요?

<img width="591" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/61a080e5-7088-420e-aed7-f8fb43c02a6e">

2023-08-16 08:17 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +    });
@hoon5083 음.. 근데 지금 selectedOption state 타입이
```
{
  children: React.ReactNode;
  value: string;
};
```
이런데, 현재 선택된 항목의 value도 isSelected props 전달할 때 필요하고, children도 현재 선택된 항목의 내용 보여줄 때 필요해서 어차피 둘 다 state로 관리해야 하는 상황이라.. 둘을 묶어서 관리하는게 편할 것 같아서 저렇게 하긴 했습니다
아니면 children도 현재 선택된 항목의 내용을 따로 state로 관리하지 않고 그때그때 value를 비교하는 방법도 있겠네요

2023-08-16 08:32 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +    });
@hoon5083 @jaychang99 selectedOptionValue (현재 선택된 항목의 value)만 state로 관리하고, 현재 선택된 항목의 children의 경우, 렌더링될 때 value 일치하는지 확인하도록 코드 수정해봤는데 확인 부탁드립니다!

2023-08-17 01:18 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    });
@sera2002 넵넵 확인하였습니다! 수고하셨습니다.

2023-08-17 01:19 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
@sera2002  넵넵 확인하였습니다. 코드상으로 그럼 `value` 값이 먼저 들어오면 이를 선순위로 이용하고, 이후에 `value` 값이 없을 경우 `<Dropdown.Option />` 중 `isSelected` 가 true 인 값을 사용하게 되는 것으로 이해했는데 맞을까요?

2023-08-17 01:35 UTC, sera2002 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
넵 맞습니다!

2023-08-17 08:21 UTC, hoon5083 commented on src/components/dropdown/Dropdown.tsx
> +    });
확인했습니다!

2023-08-17 08:21 UTC, kanghoon-dev commented on src/components/dropdown/items/DropDownOption.tsx
> +  }
확인했습니다 :)

2023-08-17 08:22 UTC, hoon5083 approved these changes
수고하셨습니다! 나머지 수정 요청 사항 확인되고 머지 조건 충족되는대로 머지해주시면 될거 같아요 :)

2023-08-17 12:21 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +  onSelectValueChange?: (value: string) => void;
@sera2002 넵 확인 감사드립니다!!

2023-08-17 12:21 UTC, jaychang99 approved these changes
LGTM 입니다. 수고하셨습니다!

2023-08-17 12:35 UTC, merged