활동 지역 선택 컴포넌트
SystemConsultantGroup/foodhub-frontend pull request #16
Opened 2023-08-26 10:34 UTC by sera2002

작성자: @sera2002 

Related to #{이슈 번호 기입}

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 단체 관련 form에 사용되는 지역 선택 컴포넌트입니다.
- Props
  - label : 인풋 라벨
  - value: 기존에 선택된 지역 id (9자리 숫자)
  - onSelectValueChange : 선택된 지역 id 콜백 함수
  
- 지역 id 파싱 방법
  - id[0] : 기본적으로 붙는 prefix (뒤의 0이 숫자로 저장될 때 생략되는 것을 방지)
  - id[1:3] (2자리) : 시·도 2자리 코드 (지정되지 않은 경우 00으로 저장)
  - id[4:7] (3자리) : 시·군·구 3자리 코드 (지정되지 않은 경우 000으로 저장)
  - id[8:11] (3자리) : 읍·면·동 3자리 코드 (지정되지 않은 경우 000으로 저장)

## 비고

- 참고 사항을 적어주세요. 코드 리뷰하는 사람이 참고해야 하는 내용을 자유로운 형식으로 적을 수 있습니다.

2023-08-26 11:00 UTC, jaychang99 commented on src/constant/area.ts
오 이 데이터를 서버에서 받아오지 않고 프론트에서 갖고 있나용?

2023-08-26 11:10 UTC, sera2002 commented on src/constant/area.ts
넵 그냥 constants에 저장된거를 사용하도록 해놨습니다

2023-08-26 11:13 UTC, jaychang99 commented on src/constant/area.ts
오... 그렇군요.. 이걸 논의하지를 않았네요... 이거는 어디 외부 API 에서 받아오는 것이 좋지 않을까 싶습니다. 혹 행정구역의 변동이 될 경우 매번 프론트 코드를 업데이트 해야 할 것 같아서요...! 슬랙에서 논의하면 좋을 것 같습니다!

2023-08-27 03:33 UTC, jaychang99 commented on src/constant/area.ts
이 [슬랙](https://systemconsult-vqd4955.slack.com/archives/C05EW6Q949E/p1693048651570599?thread_ts=1693048426.920039&cid=C05EW6Q949E) 에서 API 나오기 전까지는 우선 상수로 관리하는 것으로 되어 이 깃헙 스레드를 resolve 합니다.  @sera2002 @hoon5083

2023-08-27 14:43 UTC, jaychang99 commented
@sera2002 @hoon5083  이 PR 제목이 [활동] 지역 선택 컴포넌트인데, 현재 와이어프레임 상으로는 지역 설정은 [맛집] 에만 있고 [단체] 생성에는 지역 설정이 없습니다. 와이어프레임에 추가해두면 될까요?

2023-08-27 14:54 UTC, sera2002 commented
> @sera2002 @hoon5083 이 PR 제목이 [활동] 지역 선택 컴포넌트인데, 현재 와이어프레임 상으로는 지역 설정은 [맛집] 에만 있고 [단체] 생성에는 지역 설정이 없습니다. 와이어프레임에 추가해두면 될까요?
> 
> 노션링크: https://www.notion.so/Create-New-Group-6ee430ffda7943d3aa6337ce355c7602?pvs=4 이것도 질문있습니다. @hoon5083

2023-08-29 12:18 UTC, jaychang99 approved these changes
LGTM 입니다. 수고하셨습니다. 몇 가지 질문과 코멘트가 있으나 반드시 반영해주시지는 않으셔도 될 것 같습니다!

2023-08-29 12:18 UTC, jaychang99 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +  }, [value, sido, sigungu, dong, onSelectValueChange]);
실제로 드롭다운에 표시되는 값은 시군구 명이고, 상위 컴포넌트로 전달되는 값은 `areaId` 로 이해하였습니다. 맞나용?

2023-08-29 12:18 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    }
오 기존 정보를 참고하는 세터 함수를 부를 때는

```tsx
setIsOpen((isOpen) => (!isOpen))
```

이렇게 업데이트 함수를 넘겨주면 좋습니다. 

지금과 같이 한 번에 하나의 state 업데이트만 일어나는 경우에는 큰 차이가 없지만, 같은 state 에 대해 여러 번의 state 가 한 번의 render cycle 에 일어나는 경우 사용여부에 따라 행동하는 방식이 달라집니다. 더 자세한 정보가 궁금하다면 [이 문서](https://react.dev/learn/queueing-a-series-of-state-updates#updating-the-same-state-multiple-times-before-the-next-render:~:text=submit%20it%20again.-,Updating%20the%20same%20state%20multiple%20times%20before%20the%20next%20render,-It%20is%20an) 의 내용을 한번 읽어보세요! (5min. read)

2023-08-29 12:18 UTC, jaychang99 commented on src/components/dropdown/Dropdown.tsx
> +    max-height: 15vh;
이 값을 `vh` 로 잡아주신 이유가 있을까요~?

2023-08-29 12:40 UTC, sera2222 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +  }, [value, sido, sigungu, dong, onSelectValueChange]);
넵넵 맞습니다

2023-09-01 05:48 UTC, hoon5083 requested changes
아직 행정구역 list API가 없어서 가볍게 넘어가는게 좋겠네요 :) 

리뷰 코멘트 중 Dropdown 분리만 해주시면 어떨까 합니다 :)

2023-09-01 05:48 UTC, hoon5083 commented on src/constant/area.ts
> +export const hangjungdong = {
이 부분은 백엔드에 지역 리스트 API 추가하면 추후 PR에서 그거 적용해주시면 될 거 같아요 :)

2023-09-01 05:48 UTC, hoon5083 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +            .map((data) => (
지금은 filter 사용하셨는데, 추후에는 각각의 dropdown에서 API 호출하는 방식으로 하면 될 거 같습니다.
그거 생각하면 별도 컴포넌트로 분리하면 좋을거 같아요 :)

2023-09-01 05:48 UTC, hoon5083 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +  const [dong, setDong] = useState<string>();
이거 나중에 값 사용할때는 현재 선택한것 중 가장 작은 행정단위의 id만 보내주시면 될 겁니다! 이건 추후 API 추가하고 이야기 하시죠 :)

2023-09-07 08:44 UTC, sera2002 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +            .map((data) => (
@hoon5083 `components/inputs/AreaInput/items` 폴더에 별도의 컴포넌트로 분리해두었습니다!

2023-09-08 04:43 UTC, hoon5083 commented on src/components/inputs/AreaInput/AreaInput.tsx
> +            .map((data) => (
확인했습니다!

2023-09-08 04:44 UTC, hoon5083 approved these changes
LGTM 입니다!
API 완성되고 연결 과정에서 할 얘기들이 제법 있는것 같은데, 연결하면서 질문 많이 주시면...될거 같습니다

2023-09-10 05:34 UTC, merged