단체, 맛집, 멤버 카드를 개발합니다.
SystemConsultantGroup/foodhub-frontend pull request #18
Opened 2023-08-26 13:04 UTC by jaychang99

작성자: @jaychang99

Related to 

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 아래 이미지와 같이 단체, 맛집, 멤버를 나타내는 모바일 카드를 개발합니다. 

<img width="330" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/e0d74086-1d07-4793-96d8-8eaeb4d1a003">

## 비고

- 디자인적 테마가 구별이 뚜렷하지 않아 기존 디자인 안에서 임의로 변경한 부분이 약간씩 있습니다.

2023-08-26 14:44 UTC, sera2002 commented on src/components/dataDisplay/Restaurant.tsx
> +      {hasEditOrDeleteAuth && (
권한이 없는 경우에는 별다른 버튼이 안보이고, 상세조회를 하고 싶으면 그냥 해당 카드를 클릭만 하면 되는건가요?

2023-08-27 03:32 UTC, jaychang99 commented on src/components/dataDisplay/Restaurant.tsx
> +      {hasEditOrDeleteAuth && (
@sera2002 오 넵 맞습니다. 권한이 없는 경우에는 별다른 버튼이 안보입니다. (API 통해 인증)

앗 그리고 버튼을 눌렀을 때 어떻게 할지를 다 빼먹었네요 감사합니다 ㅎㅎ 😅  보완해서 다시 푸시하겠습니다!

2023-08-27 07:43 UTC, jaychang99 commented on src/components/dataDisplay/Restaurant.tsx
> +      {hasEditOrDeleteAuth && (
@sera2002  Organization, Restaurant 같은 경우 눌렀을 때 각 상세 페이지로 이동할 수 있도록 조치하였습니다!. Member 카드는 상세 페이지가 없어서 특별한 인터랙션을 추가하지 않았습니다. 푸시 하였습니다!

2023-08-27 15:28 UTC, sera2002 commented on src/components/dataDisplay/Restaurant.tsx
> +      {hasEditOrDeleteAuth && (
넵 확인했습니다! resolve하겠습니다.

2023-08-28 04:31 UTC, sera2002 commented on src/components/dataDisplay/Restaurant.tsx
> +    alert("맛집 삭제");
맛집 삭제 클릭 시에 맛집 삭제 컨펌 페이지 (`/restaurants/${restaurantId}/remove`)로, 인원 삭제 클릭 시 인원 삭제 컨펌 페이지 (`/member/${memberId}/remove`)로 이동하도록 해야 할 것 같습니다!

2023-08-31 13:03 UTC, jaychang99 commented on src/components/dataDisplay/Restaurant.tsx
> +    alert("맛집 삭제");
@sera2002 오 넵넵 미리 이동되도록 해두면 좋을 것 같습니다! 반영하겠습니다!

2023-09-01 06:43 UTC, hoon5083 requested changes
리뷰가 늦었습니다..
사소한 오타랑 기본 프로필 사진 관련 수정 요청 있습니다 :))

2023-09-01 06:43 UTC, kanghoon-dev commented on public/images/defaults/default-member-profile-image.jpeg
멤버 프로필은 DB의 랜덤 값에따라 달라지는데, 이거 반영해주시면 좋을거 같습니다 :) 그러려면 defaults아래에 member, organization 경로가 새로 생기면 어떨까 싶네요 :)))

2023-09-01 06:43 UTC, kanghoon-dev commented on src/components/dataDisplay/Member.tsx
> +  const handleTogglePropover = () => {
Popover인데 오타인가요?

2023-09-05 12:48 UTC, jaychang99 commented on public/images/defaults/default-member-profile-image.jpeg
@hoon5083  아하아하 그러면 

```
ㄴ defaults
  ㄴ members
    ㄴ 1.jpeg
    ㄴ 2.jpeg
    ㄴ 3.jpeg
    ㄴ 4.jpeg
    ㄴ 5.jpeg
    ㄴ 6.jpeg
...
```

이런 식의 구성을 생각하신 것일까요~?

2023-09-05 12:57 UTC, jaychang99 commented on src/components/dataDisplay/Member.tsx
> +  const handleTogglePropover = () => {
@hoon5083  오 넵!! 매의 눈이시군요!

수정하였습니다. 감사합니다!

2023-09-05 12:57 UTC, jaychang99 commented on src/components/dataDisplay/Restaurant.tsx
> +    alert("맛집 삭제");
@sera2002 반영하였습니다 감사합니다!

2023-09-08 03:55 UTC, hoon5083 commented on public/images/defaults/default-member-profile-image.jpeg
확인이 늦었습니다 :( 네 정확히 제가 생각한 바이긴 합니다...만 폴더 구조 정도는 생각하시는 제일 나은 구조로 짜주시면 될 것 같습니다.

2023-09-08 03:55 UTC, hoon5083 commented on src/components/dataDisplay/Member.tsx
> +  const handleTogglePropover = () => {
확인했습니다!

2023-09-09 05:54 UTC, jaychang99 commented on public/images/defaults/default-member-profile-image.jpeg
@hoon5083 반영하였습니다!

2023-09-10 05:39 UTC, hoon5083 commented on public/images/defaults/default-member-profile-image.jpeg
네넵 확인했습니다

2023-09-10 05:40 UTC, hoon5083 approved these changes
수고하셨습니다!

2023-09-10 05:41 UTC, sera2002 approved these changes
수고하셨습니다

2023-09-10 05:52 UTC, merged