Divider (구분선) 공통 컴포넌트를 개발합니다.
SystemConsultantGroup/foodhub-frontend pull request #4
Opened 2023-07-27 12:55 UTC by jaychang99

작성자: @jaychang99 

Related to #

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [x] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- 구분선인 `<Divider />` 컴포넌트를 개발합니다. 
  - optional 한 prop인 `width` 를 받으며, 숫자값이 입력될 경우 px 로 너비가 지정되며, 입력되지 않을 경우 컨테이너의 100% 를 차지합니다!
- 이외 emotion 기본 타이핑 작업들과 공통  shadow 를 셋업합니다. 

![image](https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/9fb05190-fd48-4bc0-bfbd-d21ea10f39a3)

## 비고

- 공통 사항이 있어 빨리 머지되면 좋을 것 같습니다!

2023-07-28 04:38 UTC, sera2002 approved these changes

2023-07-28 04:38 UTC, sera2002 commented on src/components/divider/Divider.tsx
컴포넌트 파일 이름은 (폴더 소문자 + 파일 대문자)로 통일하면 되는 건가요?

2023-07-28 05:06 UTC, hoon5083 commented on src/components/divider/Divider.tsx
어.. 폴더명도 대문자로 해야 한다고 했던거 같은데, 실수하신거 같긴 합니다 :)

2023-07-28 09:55 UTC, jaychang99 commented on src/components/divider/Divider.tsx
@sera2002 

현재로서는 [폴더명] 은 안에 컴포넌트가 들어있든, 함수 파일, 또는 이미지 등 어떤 것이 들어있어도 camelCase 로 가려고 합니다. (첫소문자, 이후부터 대문자)
그리고 [컴포넌트명 (컴포넌트가 들어간 파일명 포함)] 은 PascalCase (모두 대문자) 로 가려고 합니다~

**예외: src/pages 안에 들어가는 컴포넌트는 파일명 자체가 url 이므로 전부 소문자 (또는 URL 에 맞게 지정) 합니다. 대신 파일명 안의 페이지 컴포넌트 그 자체는 리액트 컴포넌트 명명 규칙에 따라 반드시 PascalCase 로 작성하여야 합니다.**

ex) `src/pages/groups.tsx` 안에서


```
tsx
export const PageGroups = () => {
  const foo = 3

  return (
    <div />
  )
}
```


이렇게 하면 될 것 같습니다~ Page* 는 그냥 임의로 이것이 페이지임을 구분하기 위해 붙여본 접두어입니다!

2023-07-28 13:26 UTC, hoon5083 requested changes
수고하셨습니다! 그림자 관련해서 사소한 제안이 있습니다 :)

2023-07-28 13:26 UTC, hoon5083 commented on src/components/divider/Divider.tsx
저는 사실 페이지 컴포넌트에 ~~~~Page 이런식으로 접미어로 붙이곤 합니다 ㅎ

2023-07-28 13:26 UTC, hoon5083 commented on src/styles/theme.ts
> +  },
hover나 click시의 것도 미리 정의해 두면 어떨까요? 두세 단계 정도면 충분할 거 같기는 합니다 :)

2023-07-28 14:42 UTC, jaychang99 commented on src/styles/theme.ts
> +  },
오 넵넵 좋은 아이디어네요!!

구분선 같은 경우 인터랙션이 없지만 클릭 가능한 항목들의 경우 정의를 하두면 좋을 것 같습니다. 반영해서 다시 푸시하겠습니다!  @hoon5083

2023-07-28 15:48 UTC, hoon5083 commented on src/components/divider/Divider.tsx
본 스레드 해결 됐다고 봐도 될 것 같은데, resolve 부탁드립니다 :) @sera2002

2023-07-29 00:05 UTC, jaychang99 commented on src/styles/theme.ts
> +  },
@hoon5083 그림자를 어떻게 처리하는 것이 좋을까요?

기본의 경우 있고, hover 시 더 연하게? 클릭 상태에서는 기본보다 더 진하게? 이렇게인가요? 😓

2023-07-29 00:43 UTC, jaychang99 commented on src/styles/theme.ts
> +  },
@hoon5083 @sera2002 @2Natrium  

우선 아래와 같이 interactive 하게 적용해보았습니다...
뭔가 조금 어색하긴 한데 사용하실 때 아래와 같이 `interactiveShadow.ts` 내용 써주시면 이상해도 일괄 변경 가능할 것 같습니다.~!



https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/658ba1fe-e511-4a57-8cd8-b98b59de4d28



```tsx
 .shadow-test {
    width: 100px;
    height: 100px;
    border-radius: 25px;
    ... { 나머지 CSS 속성들 }
    ${interactiveShadow}
  }
```

2023-07-29 00:49 UTC, jaychang99 commented on src/styles/theme.ts
> +  },
아 참고로 배경색은 `gray100` 적용해보았는데 괜찮네용

2023-07-29 05:51 UTC, hoon5083 commented on src/styles/theme.ts
> +  },
좋습니다!

2023-07-29 05:52 UTC, hoon5083 commented
수고하셨습니다!

2023-07-29 05:55 UTC, hoon5083 approved these changes

2023-07-29 05:56 UTC, hoon5083 commented
수고하셨습니다!

2023-07-29 06:06 UTC, merged