Button 공통 컴포넌트를 개발합니다.
SystemConsultantGroup/foodhub-frontend pull request #7
Opened 2023-08-01 07:42 UTC by sera2002

작성자: @sera2002 

Related to (이슈를 만들지 않았습니다.)

## 체크 리스트

- ✅ 적절한 제목으로 수정했나요?
- ✅ 상단에 이슈 번호를 기입했나요?
- ✅ Target Branch를 올바르게 설정했나요?
- ✅ Label을 알맞게 설정했나요?

## 작업 내역

- Button 컴포넌트 스타일 설정 (primary, secondary, text, icon, icon with text)
- Loading 스피너 설정

## 비고

- widthType은 버튼의 width를 hug(default)로 할 지 아니면 부모 컴포넌트의 너비에 맞출지(fullWidth)를 설정하는 props입니다.

2023-08-01 13:53 UTC, jaychang99 reviewed
오 첫 컴포넌트 수고하셨습니다! 몇 가지 코멘트와 질문을 남겨보았습니다!

2023-08-01 13:53 UTC, jaychang99 commented on public/images/Spin-1s-100px-gray.svg
오 로더군요!!

로더를 이미지 형식으로 불러와도 괜찮을까요? @hoon5083 @Kangdyu 
이를테면 이미지를 로딩하는 동안 로더를 표시할 수도 있는데 로더 자체가 이미지이면 로더 표시가 느려질 수 있을 것 같아 로더는 순수 CSS 로 구현하는 것이 어떨까 싶기도 해서요...!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  variant?: "primary" | "secondary" | "text" | "icon" | "iconWithText"; // color types
오.. variant 가 다양하군요!

이건 제 디자인 미스인 것 같습니다. ㅜ.ㅜ

모든 종류의 버튼에는 아이콘이 들어갈 수 있는 것으로 생각하고 디자인 하긴 했습니다 ㅎ

그렇다면  `icon` 을 옵셔널하게  props 로 받아 icon 값이 주어지면  14*14 사이즈로 글씨 옆에 보여주고, 주어지지 않으면 아이콘을 노출하지 않는 것은 어떨까요~?

```suggestion
  variant?: "primary" | "secondary" | "text" | "icon" ; // color types
  icon?: React.ReactNode;
```

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  widthType?: "default" | "fullWidth"; // default : hug
오 좋아요!

다만 저희 디자인 상 `default` 도 많이 쓰지만 `fullWidth` 도 꽤 많이 쓸 것 같기도 하며, 현재 종류가 2가지 밖에 없어 `fullWidth` 라는 boolean props 를 받는 형식은 어떨까요?

```suggestion
  fullWidth?: boolean // default : false
```

이러면 사용처에서 바로 

```tsx
  <Button fullWidth /> { /* 길쭉버튼 */}
  <Button /> { /* 일반버튼 */}
```

등으로 쓸 수 있을 것 같습니다!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  onClick?: () => void;
`onClick` 속성은 `ButtonHTMLAttributes<HTMLButtonElement>` 의 기본 `<button />` element 속성이라 따로 지정해주지 않아도 괜찮을 것 같습니다!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  };
요 부분은 로딩 상태를 mocking 하기 위해 만들어 주신 것일까요~?

현재 타입으로는 `onClick` 으로 넘어온 함수가 Promise 를 반환하는 함수가 아니라 `await` 문이 효과가 없을 것 같기는 합니다...! 로딩상태의 경우 'isButtonLoading' 의 컴포넌트 내부 state 가 아니라  `loading` props 에 전적으로 의존해야 하지 않을까 싶습니다...!

그리고 만약 Promise 를 반환한다 하더라고 이용처에서 꼭 비동기 함수를 넘기지 않을 수도 있을 것 같아, onClick 을 넘겨서 Button 을 사용하는 쪽에 loading state 관리 책임을 넘기는 것이 어떨까 싶습니다...!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +      disabled={isButtonLoading}
오...! 로딩 시 disabled 처리 좋아요!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +      {...props}
오 destructuring operator (객체 구조 분해) 연산자는 저는 보통 맨 앞에 써 줍니다...!

지금의 경우 대부분의 props 가 분해되어 상관이 없을 것 같은데, 혹시 특정하게 지정해둔 property 들이 뒤에 오는 `{ ...props }` 가 가진 같은 키값에 의해 덮어써질 수도 있을 우려가 있어 그냥 저의 작은 습관입니다..! ㅎ

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +        <Image src="/images/Spin-1s-100px-gray.svg" alt="Loading Spinner" width={14} height={14} />
스피너 (로더) 를 이미지로 불러오면 스피너를 로딩하는 시간도 걸릴 것 같아 스피너는 순수 css 로 구현하는 것이 어떨까 싶습니다...! @hoon5083 @Kangdyu 

https://cssloaders.github.io/

이런 제너레이터를 이용해볼 수도 있을 것 같습니다..!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +export const EmotionWrapper = styled.button<Props>`
오 타입처리 좋아요!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    viewBox="0 0 14 14"
이부분 혹시 타입에러 뜨지 않으셨나용? (밑에 빨간줄이요..!)

![image](https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/78b47c7d-da33-44c0-9a8c-436dc9933b22)

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +
```suggestion
  line-height: 1.5
```

가 추가되면 좋을 것 같습니다..! (디자인 안 기준)

현재 버튼이 디자인 보다 약간 납작(?) 한 느낌이 있어서요..!
![image](https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/799a878d-e8d3-4f70-a7cc-1bbe6862bf9f)

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  }
> 글자는 <Button><span>Text</span></Button>과 같이 span 안에 넣어주어야 합니다.

오.. 만약 `typeof children === "string"` 이라면 <span> 안에 감싸 넣어주는 것은 어떨까요~?
사용처에서 텍스트를 매번 span 으로 감싸는 것은 약간 불편할 수 있을 것 같습니다...!

2023-08-01 13:53 UTC, jaychang99 commented on src/components/button/Button.tsx
> +const Button = ({
버튼을 클릭하고 나서 다시 hover 하면 hover 가 안 먹는 문제가 있는 것 같습니다..!

2023-08-01 13:55 UTC, jaychang99 commented on src/components/button/Button.tsx
> +
컬러도 primary 일 경우 흰색 적용되어야 할 것 같습니다!

2023-08-01 14:12 UTC, hoon5083 commented on public/images/Spin-1s-100px-gray.svg
특히 gif기도 해서 로더를 로딩하는(?) 시간이 좀 애매해 질것 같긴 합니다! 제법 난이도 있는 CSS 사용이 되겠군요.....

2023-08-01 14:13 UTC, jaychang99 commented on public/images/Spin-1s-100px-gray.svg
오 .. 그렇긴해요 근데 아래에도 적어두었듯 https://cssloaders.github.io/ 이런 사이트를 이용해보면 어떨까 싶습니다!

2023-08-01 14:15 UTC, hoon5083 commented on src/components/button/Button.tsx
> +  variant?: "primary" | "secondary" | "text" | "icon" | "iconWithText"; // color types
근데 icon과 iconWithText의 구분을 어떻게 해야 할까요....? children 여부로 하면 될까요?

2023-08-01 14:16 UTC, hoon5083 commented on src/components/button/Button.tsx
> +  widthType?: "default" | "fullWidth"; // default : hug
Props를 boolean으로 하면 이게 편하더군요 ㅋㅋㅋ 전 좋다고 봅니당

2023-08-01 14:17 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  variant?: "primary" | "secondary" | "text" | "icon" | "iconWithText"; // color types
@hoon5083 음 ... 그것도 좀 애매하네요. 차라리 `icon` 타입도 없애고, 

* `icon` 있음, children 없음 => 아이콘만 있는 정방형버튼
* `icon` 있음, children 있음 => (기존의) `iconWithText` 

이렇게 되는 것은 어떨까요?

2023-08-01 15:00 UTC, kanghoon-dev requested changes
세라님 첫 PR이네요! 다소 코멘트가 많은데, 천천히 읽어보고 대응해주시면 될 거 같습니다 :)

2023-08-01 15:00 UTC, kanghoon-dev commented on public/images/Spin-1s-100px-gray.svg
오 역시 누군가 해둔것이...... 좋습니다!

2023-08-01 15:00 UTC, kanghoon-dev commented on src/components/button/Button.tsx
> +      {...props}
Webstorm을 쓰면 덮어씌워진다고 경고해줍니다...ㅎㅎ 전도사 등장

2023-08-01 15:00 UTC, kanghoon-dev commented on src/components/button/Button.tsx
> +    viewBox="0 0 14 14"
근디 이거 어떻게 커밋이 됐....죠??

2023-08-01 15:00 UTC, kanghoon-dev commented on src/components/button/Button.tsx
> +const Button = ({
이거 focus가 안 풀려서 그런것 같네요 :( focus에서 hover와 공통되는 속성 (여기서는 background-color)을 정의하는게 문제가 되는 거 같습니다! 근데 click하는 상황이라 focus(tab을 눌러서)되는 상황을 보통 어떻게 구분하죠....?

2023-08-01 15:00 UTC, kanghoon-dev commented on src/components/button/styles.tsx
> +};
여기서 isLoading을 받기보다는 컴포넌트 측에서 isLoading이 true이면 추가해주는 식으로 컴포넌트 파일쪽에 넣으면 어떨까요?
@jaychang99

2023-08-01 15:05 UTC, hoon5083 commented
추가로, @jaychang99 님이 만들어 두신 interactiveShadow 사용하시면 코드 반복이 줄어들거 같습니다!

2023-08-03 02:53 UTC, sera2002 commented on src/components/button/Button.tsx
> +  variant?: "primary" | "secondary" | "text" | "icon" | "iconWithText"; // color types
넵넵 좋습니다! @jaychang99 님 말씀대로 해보겠습니다.

2023-08-05 13:07 UTC, sera2002 commented on src/components/button/Button.tsx
> +  }
span으로 감싸지 않아도 되도록 수정하겠습니다..!

2023-08-05 13:08 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    viewBox="0 0 14 14"
@hoon5083 음... husky 가 적용이 안 되었을까요

2023-08-05 13:09 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  }
@sera2002  오 넵넵 감사합니다. 혹시 확인할 수 있게 코드 푸시 가능하실까요~?

2023-08-05 13:26 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  const [padding, setPadding] = useState("4px 15px");
@sera2002 앗 혹시 `padding` 값을 state 로 관리하도록 한 이유가 있을까요~?

2023-08-05 13:29 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  fullWidth: boolean;
@sera2002 `fullWidth` prop 의 경우 아래에서 기본값 처리가 false 로 되어 있어  optional 하게 받아도 될 것 같아요!

2023-08-05 17:00 UTC, sera2002 commented on src/components/button/Button.tsx
> +  }
[이 커밋](https://github.com/SystemConsultantGroup/foodhub-frontend/pull/7/commits/959a58e48296ce3c199bd331a5df0b473616fc7e)에서 반영하였습니다!

2023-08-06 01:53 UTC, jaychang99 commented on src/components/button/styles.tsx
> +};
@hoon5083  넵 그런 방식이 좋은 것 같습니다.

2023-08-06 01:54 UTC, jaychang99 commented on src/components/button/Button.tsx
> +const Button = ({
어 탭누른 상태면 focus, 클릭된 상태는 active아닌가요~? @hoon5083

2023-08-06 01:55 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  }
@sera2002 넵넵 확인했습니다~ 감사합니다!

2023-08-06 01:56 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    }
아 요게 그 focus. 풀리지 않는 문제 해결하는 코드인가요~?

2023-08-06 01:57 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  onClick?: () => void;
이부분 해결된 것 같아 resolve 합니다~수고 하셨습니다~

2023-08-06 01:57 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  };
이부분 해결된 것 같아 resolve 합니다~수고 하셨습니다~

2023-08-06 01:57 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  variant?: "primary" | "secondary" | "text" | "icon" | "iconWithText"; // color types
이부분 해결된 것 같아 resolve 합니다~수고 하셨습니다~

2023-08-06 01:59 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    viewBox="0 0 14 14"
@sera2002 혹시 커밋하실 때 터미널에서 뭔가 체크하듯이 돌았었나요? (husky)

2023-08-06 01:59 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  }
엇 이제 이 스타일은 지워도 되지 않을까요~?

2023-08-06 02:00 UTC, jaychang99 commented on src/components/button/Button.tsx
> +
이부분 해결된 것 같아 resolve 합니다~ 수고하셨습니다!

2023-08-06 02:01 UTC, jaychang99 commented on src/components/button/Button.tsx
> +      {loading && <Loader></Loader>}
self-closing 태그를 이용하면 가독성이 좀 더 좋아질 것 같아요!

2023-08-06 02:03 UTC, jaychang99 commented on src/components/loader/styles.module.css
엇 혹시 이부분만 css module 로 처리하신 이유가 있으실까요~?

2023-08-06 02:03 UTC, jaychang99 commented on src/components/button/Button.tsx
> +        <Image src="/images/Spin-1s-100px-gray.svg" alt="Loading Spinner" width={14} height={14} />
우선 해결된 것 같아 resolve 합니다. 다만, Loader 에서만 스타일을 CSS module 로 사용하신 점은 별개의 스레드로 질문드려 두었습니다~!

2023-08-06 02:04 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  widthType?: "default" | "fullWidth"; // default : hug
해결된 것 같아 Resolve 합니다~

2023-08-06 02:04 UTC, jaychang99 commented on public/images/Spin-1s-100px-gray.svg
이것도 해결되었지만, Loader 에 적용된 스타일만 CSS module 을 사용한다는 점을 별도 스레드에서 질문드렸습니다~

2023-08-06 02:05 UTC, jaychang99 commented on src/components/button/styles.tsx
> +};
넵 이거 해결된 것 같아 Resolve 해도 될까요~? 
제가 최초 작성한 리뷰가 아니라서 resolve 하기가 좀 애매하네요 ㅎ

2023-08-06 02:05 UTC, jaychang99 commented on src/components/button/Button.tsx
> +  fullWidth: boolean;
확인했습니다!

2023-08-06 17:44 UTC, hoon5083 commented on src/components/button/Button.tsx
> +const Button = ({
넵 근데 클릭을 해도 focus가 들어가긴 하지 않나요?

2023-08-06 17:44 UTC, hoon5083 commented on src/components/button/styles.tsx
> +};
확인했습니다!

2023-08-06 17:45 UTC, hoon5083 commented on src/components/button/Button.tsx
> +    }
오... 이거 document 객체에 직접 접근하는게 괜찮을까요...?

2023-08-08 06:29 UTC, hoon5083 commented
이슈번호 기입하지 않을 경우에는 체크리스트에서 하나 빼주세요 :)

2023-08-12 07:33 UTC, jaychang99 approved these changes
긴 PR 수고하셨습니다! 🎉

2023-08-13 00:02 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    viewBox="0 0 14 14"
- 슬랙에서 계속 (관련 [슬랙](https://systemconsult-vqd4955.slack.com/archives/C05EW6Q949E/p1691884945793899?thread_ts=1691822336.342489&cid=C05EW6Q949E))

2023-08-13 00:15 UTC, jaychang99 commented on src/components/button/Button.tsx
> +const Button = ({
@hoon5083 오 그래요? 음... 원래도 그럼 클릭 최초 1회 하면 focus 가 걸렸었는데 저희가 이때까지 별도의 스타일을 추가하지 않아서 문제가 없었던 것일까요...?

2023-08-13 00:16 UTC, jaychang99 commented on src/components/button/Button.tsx
> +    }
@hoon5083 오 `ref` 로 잡아주는 게 좋을 것 같습니다...! @sera2002

2023-08-13 09:06 UTC, hoon5083 commented on src/components/button/Button.tsx
> +const Button = ({
네 아마 그렇지 않나... 생각하고 있습니다

2023-08-13 17:38 UTC, hoon5083 approved these changes
제 스레드 다 resolve하면서 approve 할걸 늦어졌네요 :(( 수고하셨습니다!

2023-08-14 02:56 UTC, merged