페이지 골격을 세팅합니다.
SystemConsultantGroup/foodhub-frontend pull request #9
Opened 2023-08-06 14:41 UTC by jaychang99

작성자: @jaychang99 

Related to (이슈 미작성)

## 체크 리스트

- [x] 적절한 제목으로 수정했나요?
- [ ] 상단에 이슈 번호를 기입했나요?
- [x] Target Branch를 올바르게 설정했나요?
- [x] Label을 알맞게 설정했나요?

## 작업 내역

- PC 와 Mobile 에 대해 기본 화면 레이아웃 작업을 합니다. 
  - PC, Mobile 모두 하단  `<Navbar />` 는 있으나, 상단 헤더 디자인이 다르게 반영됩니다. 
- PC, Mobile 브레이크 포인트는 768px (갤럭시폴드 펼쳤을 떄) +  좌우여백 각 40px , 해서 총 848px 입니다. 
- `<PageMarker />` 임시 컴포넌트를 통해 페이지 골격만 있고, 완성되지 않은 페이지를 나타내는 데에 사용할 수 있습니다. 
- 아래 페이지를 모두 잡아 두었습니다. (제 담당 페이지)
  - 로그인, 회원가입
  - 맛집 리스트 (+맛집 상세 => 같은 폴더라 같이 잡아두었습니다)
  - 단체 리스트 (+단체 상세 => 같은 폴더라 같이 잡아두었습니다)
  - 투표 페이지 전체
- 커스텀 에러 페이지가 추가되었습니다. 
  - `_error.tsx` 의 <CustomError />` 페이지입니다. 이제 서버 사이드에서 특정 조건에 따라 에러 페이지를 떨어뜨릴 수 있습니다. 

<img width="429" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/2d42f3f4-4dbc-4f82-b3ca-e03a255dabbd">
<img width="428" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/042b6266-87b0-44de-99df-fbb2fc525e9f">
<img width="1511" alt="image" src="https://github.com/SystemConsultantGroup/foodhub-frontend/assets/86560973/e69ce107-4684-4f05-a07b-9356559c504f">

## 비고
- 남은 작업 : 아이콘 컴포넌트화하기 => 아직 진행되지 않았습니다. (빠른 코드리뷰를 위해 선 PR 올립니다!)

2023-08-08 05:57 UTC, hoon5083 requested changes
질문 몇가지, 수정 제안 1가지가 있습니다 :)

2023-08-08 05:57 UTC, hoon5083 commented on src/components/layout/Layout.tsx
> +      <HeaderMobile />
요거 PC 환경에서 헤더가 항상 떠있는다고 생각하니까 다소 화면을 많이 잡아 먹는다는 생각이 드는데, 메인에서만 뜨게 하고, 이후에는 그냥 상단 네비게이션만 보여주는 건 어떨까요? MobileHeader를 조금 변형하면 가능할 것 같습니다.

(현)MobileHeader를 항상 보여주게 하고 (포함되는 컴포넌트는 달라질수도), DesktopHeader를 추가해 주는 방식으로요.

일단 모바일 환경에서는 적절히 잘 나오는 것 같습니다

2023-08-08 05:57 UTC, hoon5083 commented on src/components/pageMarker/PageMarker.tsx
> +      <p className="under-construction">🚧 공사중 🚧</p>
공사중 이모지 귀엽네요 ㅋㅋㅋㅋㅋㅋ

2023-08-08 05:57 UTC, hoon5083 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
요기 랜덤한 기본 이미지 보여주기로 했는데, 그거 맞춰서 살짝 수정해두면 연결할때 편할 것 같습니다

```suggestion
        src={src ?? `/images/profile-image-default-${defaultPhotoId}.png`}
```

2023-08-08 05:57 UTC, hoon5083 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
API 문서에 1차로 유저 부분은 작성되어 있긴 해서, 그거 참고하셔도 될 듯 합니다

2023-08-08 05:57 UTC, hoon5083 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
아주아주 사소하지만... 짧게 "오늘 뭐 먹지." 도 괜찮을 것 같아요 ㅋㅋㅋㅋ

2023-08-08 05:57 UTC, hoon5083 commented on src/pages/login/index.tsx
> +    res.writeHead(302, { Location: "/" });
혹시 이거(+전체적으로) 302 사용하신 이유가 있을까요? SEO 측면에서 메인 페이지에 페이지 랭크를 높게 유지하려면 301이 더 낫지 않나 싶어서요

2023-08-08 10:29 UTC, jaychang99 reviewed
리뷰 감사합니다~ 질문에 대한 답변 및 수정 방향성을 제안하였습니다!

2023-08-08 10:29 UTC, jaychang99 commented on src/components/layout/Layout.tsx
> +      <HeaderMobile />
@hoon5083 오 맞네요.. 애초에 기획도 이 헤더는 메인페이지에서만 뜨는게 맞습니다. ㅎㅎ

말씀주신 것처럼 이 섹션은 `<Hero />` 등으로 변경하고... 헤더를 두개 만들면 좋을 것 같습니다~!

2023-08-08 10:29 UTC, jaychang99 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
오 넵넵 그래도 '어디서' 가 꼭 들어가면 좋다고 생각합니다..!

'오늘 어디서 먹지?' 는 어떨까요? ㅎ

2023-08-08 10:29 UTC, jaychang99 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
@hoon5083  아 맞네요 죄송합니다. 그 랜덤으로 6개 (?) 정도 암튼 돌아가면서 랜덤하게 생성되기로 한거 그거에 대응해야겠네요. 알려주셔서 감사합니다 🙏

2023-08-08 12:21 UTC, hoon5083 commented on src/components/layout/Layout.tsx
> +      <HeaderMobile />
아하 ㅋㅋㅋㅋ 말씀드린 기조는 유지하고, 편하신대로 구성해주시면 될 것 같아요 :)

2023-08-08 12:23 UTC, hoon5083 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
오오오오 그럼 이거 어울림때처럼
오늘 (어디서/뭐/누구랑) 먹지?
이렇게 주기적으로 반복되면서 나오는건 어떤가요?????

2023-08-10 23:44 UTC, jaychang99 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
@hoon5083 엌ㅋㅋㅋㅋㅋㅋㅋㅋ 재탕쓰... 느낌이 들긴 하지만 좋은 아이디어 같습니다 ㅎ

2023-08-12 01:27 UTC, jaychang99 commented on src/components/layout/Layout.tsx
> +      <HeaderMobile />
오 넵 변경하여 보았습니다! @hoon5083

2023-08-12 01:33 UTC, jaychang99 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
@hoon5083  대응해 보았습니다!

2023-08-12 01:55 UTC, jaychang99 commented on src/pages/login/index.tsx
> +    res.writeHead(302, { Location: "/" });
@hoon5083 오 예리하고 꼼꼼한 포인트군요. 

우선 301 의 경우 Permanent Redirect 로 알고 있습니다. 
그런 고로, 저희가 `/login` 페이지를 (사실 login 페이지는 인덱싱되지 않아도 크게 문제 없지만) 301 로 리다이렉트하면 추후 SEO 에서 login 페이지가 메인으로 변경되었는 것이라고 인식할 것이라고 생각했습니다. 

그에 비해 302 는 temporary redirect 로 이렇게 원래 페이지도 계속 사용될 때 사용할 수 있을 것이라고 생각했습니다. 
그리고 봇이 크롤링 할 때에는 무조건 accessToken 없이 요청을 보내게 될 것이므로 redirect 에 큰 영향을 받지 않지 않을까요(?)

2023-08-12 01:56 UTC, jaychang99 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
@hoon5083  이 작업은 공수가 좀 들것 같고, 페이지 골격 세팅 작업과 관련도가 다소 낮은 것 같아 별개 PR 로 추후 대응할 수 있도록 하면 어떨까요~?

현재 메인페이지 작업인 선순위 작업이 있어서 그렇습니다!

2023-08-12 01:57 UTC, jaychang99 commented
@hoon5083  1개 리뷰 제외 모든 리뷰를 반영 완료하였습니다. 

`<Hero />` 에서 어디서/뭐/누구랑 이부분은 공수가 좀 들 것 같아 별개 이슈로 준비해두고 추후 만들면 좋지 않을까 생각했습니다!

2023-08-12 02:40 UTC, jaychang99 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
차라리 그냥 아무 props 도 받지 않게 하는 것도 방법일 거 같습니다. 

인증과 유저데이터 한번더 프로필 내부에서 받아오고, 생각해보니 이 컴포넌트가 props 를 받을 이유가 없는 것 같은데요? ㅎ

2023-08-12 14:06 UTC, hoon5083 commented on src/pages/login/index.tsx
> +    res.writeHead(302, { Location: "/" });
오호.... 알겠습니다 사실 저도 얼마전에 심심해서 http 상태코드 문서 정독하면서 알게 된거라서요 ㅋㅋㅋㅋ 일단 상관 없을 것 같습니다 :) resolve 하겠습니다!

2023-08-12 14:07 UTC, hoon5083 commented on src/components/header/Header.tsx
> +        <p className="main-question">... 우리 이번에 어디서 밥먹지? </p>
네넵 좋습니다 :) 추후에 header 파트 구현 배정 해보죠 :)

2023-08-12 14:09 UTC, hoon5083 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
그러게요 그게 더 나을 것 같습니다! 어차피 SWR 쓰니까 알아서 캐싱하고 요청 날려주기도 하고...

2023-08-12 14:09 UTC, hoon5083 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
말씀하신대로 변경하신거 확인하면 바로 resolve하겠습니다 :)

2023-08-12 14:10 UTC, hoon5083 commented on src/components/layout/Layout.tsx
> +      <HeaderMobile />
확인했습니다!

2023-08-15 00:50 UTC, jaychang99 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
@hoon5083  오 확인이 늦어 죄송합니다! 수정 하여 다시 push 하였습니다. 

만드는 과정 중에 데이터 같은 경우 내부적으로 받으면 되지만, 프로필 사진을 다양한 크기로 이용하고 싶은 경우를 고려하여 `size` prop (옵셔널, 기본값 30, (가로/세로 값으로 이용)) 을 추가했습니다. (마이페이지에는 큰 크기로 사용하여야 하는 점 고려)

2023-08-15 05:23 UTC, hoon5083 commented on src/components/profileImage/ProfileImage.tsx
> +        src={src ?? "/images/profile-image-default.png"}
확인했습니다!

2023-08-15 05:23 UTC, hoon5083 approved these changes
수고하셨습니다 :)

2023-08-16 02:42 UTC, sera2002 approved these changes

2023-08-16 13:22 UTC, merged